# >>> Basic Setup | åŸºç¡€è®¾ç½® <<<

# Header | ä¸»èœå•
## About Page: `hexo new page about`
## Tags Cloud Page: `hexo new page tags`
menu:
  # ä¸»é¡µ: /archives/
  æ‰€æœ‰æ–‡ç« : /archives/
  React: /categories/react
  Redux: /categories/redux
  JavaScript: /categories/javascript
  å‰ç«¯: /categories/frontend
  # å‰ç«¯å¿…å¤‡: /categories/å‰ç«¯å¿…å¤‡
  # tips: /categories/tips
  # å…³äºæˆ‘: /about/
# é™å¿ƒé˜…è¯»: /tags

# Link to your avatar | å¡«å†™å¤´åƒåœ°å€
avatar: /img/ali.png

# Small icon of Your site | ç«™ç‚¹å°å›¾æ ‡åœ°å€
favicon: /img/thumbsup.jpg

# åŸŸåæ˜¯å¦å¯ç”¨httpsï¼Œå¦‚æœå¯ç”¨ï¼Œjsæ–‡ä»¶å¿…é¡»httpsåŠ è½½
isHttps: true

# Social info. Bar | ç¤¾äº¤ä¿¡æ¯å±•ç¤º
## Keep "mailto:" in Email | è®¾ç½® Email æ—¶ä¿ç•™ "mailto:"
## Encrypt email åŠ å¯†é‚®ä»¶åœ°å€ http://ctrlq.org/encode/
## RSS requires a plugin to take effect | ä½¿ç”¨ RSS éœ€å…ˆå®‰è£…å¯¹åº”æ’ä»¶
## https://github.com/hexojs/hexo-generator-feed
subnav:
  github: https://github.com/chenhx2015/
  # weibo: xxxxxxxx
  rss: /atom.xml

  # Google: "#"

# >>> Conments è¯„è®ºç³»ç»Ÿ <<<

disqus:
  on: false
  shortname: xxxxxxxxx
  # https://help.disqus.com/customer/en/portal/articles/466208-what-s-a-shortname-
  # It is unnecessary to enable disqus here if
  # you have set "disqus_shortname" in your site's "_config.yml"
changyan:
  on: false
  appid: xxxx
  conf: xxxxxxxxx
  # æ˜¯å¦å¼€å¯ç•…è¨€è¯„è®ºï¼Œ
  # id ä¸­å¡«å†™ä½ çš„å‹è¨€ç”¨æˆ·æ•°å­—IDï¼Œæ³¨å†Œåè¿›å…¥åå°ç®¡ç†å³å¯æŸ¥çœ‹
  # ç•…è¨€è¯„è®ºåœ¨ Web ç¯å¢ƒä¸‹è¿è¡Œï¼Œæ™®é€šæœ¬åœ°ç¯å¢ƒæ— æ³•æŸ¥çœ‹ï¼Œè¯·éƒ¨ç½²ååœ¨çº¿ä¸Šæµ‹è¯•ã€‚
gitment:
  on: false
  githubID: yourid
  repo: yourrepo
  client_id: yourid
  client_secret: yoursecret
  lazy: true

# >>> Style Customisation æ ·å¼è‡ªå®šä¹‰ <<<

# Background | èƒŒæ™¯
## "background_sum": show images form /source/background/çš„å›¾ç‰‡æ•°ç›®
## "on: true": è‡ªåŠ¨éšæœºæ˜¾ç¤ºè¿™5å¼ å›¾ç‰‡
## "on: false": è‡ªå®šä¹‰æ˜¾ç¤ºå›¾ç‰‡è®¾ç½®background_image: 5
background:
  on: true
  background_sum: 1
  background_image: 1

highlight_style:
  on: true
  inline_code: 3 # Value: 0 - 9 å¯é€‰
  code_block: 2 # Value: 0 - 4
  # Set inline_code to style highlight text
  # Chose a highlight theme for code block
  # é€šè¿‡ inline_code åˆ‡æ¢å†…ç½®æ–‡æœ¬é«˜äº®æ ·å¼
  # é€šè¿‡ code_block åˆ‡æ¢å†…ç½®ä»£ç é«˜äº®é…è‰²ä¸»é¢˜

blockquote_style:
  #on: true
  blockquote: 5 # Value: 0 - 7 å¯é€‰
  # è‡ªå®šä¹‰æ–‡ç« ã€Œå¼•ç”¨éƒ¨åˆ†ã€çš„æ ·å¼

# å·¦è¾¹æ å®½åº¦ px
left_col_width: 300

# ç›®å½•ä¸­æ ‡é¢˜ä¸æ¢è¡Œ
# Keep TOC title on the same line |
toc_nowrap: false

# è‡ªå®šä¹‰"é˜…è¯»å…¨æ–‡"é“¾æ¥æŒ‰é’®çš„æ˜¾ç¤ºæ–‡å­—
# Customize the text on excerpt link
excerpt_link: æŸ¥çœ‹æ›´å¤š #ä¿®æ”¹more>>çš„æ–‡å­—

# æ˜¯å¦æ˜¾ç¤ºè¾¹æ ä¸­çš„æœç´¢æ¡†ï¼ˆç«™å†…æœç´¢ï¼‰
# Search Box in left column
search_box: false

# æ˜¯å¦å¼€å¯ä¸»é¡µåŠåŠ è½½å¤´åƒæ—¶çš„åŠ¨ç”»æ•ˆæœ
# Animation in Homepage and Loading avatar
animate: true

# >>> Small features | å°åŠŸèƒ½è®¾ç½® <<<

# æ˜¯å¦å¼€å¯è¾¹æ å¤šæ ‡ç­¾åˆ‡æ¢
# Birdhouse button in left column
tagcloud: true

# Blogroll, Link exchange | å‹æƒ…é“¾æ¥
friends: false
# friends:
#   csdn: http://blog.csdn.net/baidu_21483933
#   segmentfault: https://segmentfault.com/blog/maocg_web
#   ç®€ä¹¦: http://www.jianshu.com/users/eb37ef89c746/latest_articles
#æ˜¯å¦å¼€å¯â€œå…³äºæˆ‘â€ã€‚
aboutme: çˆ±ç¼–ç¨‹ï¼Œçˆ±ç¡è§‰ğŸ˜ª
#aboutme: false

# æ˜¯å¦åœ¨æ–°çª—å£æ‰“å¼€é“¾æ¥
open_in_new: false

# Customize feed link è‡ªå®šä¹‰è®¢é˜…åœ°å€
rss: /atom.xml

# >>> Vendors | ç¬¬ä¸‰æ–¹å·¥å…· & æœåŠ¡ <<<

# images viewer | å›¾ç‰‡æµè§ˆå™¨
## http://www.fancyapps.com/fancybox/
fancybox: true

# Display Math(LaTeX, MathML...) | æ•°å­¦å…¬å¼æ”¯æŒ
## https://www.mathjax.org/
mathjax: false

# Socail Share | æ˜¯å¦å¼€å¯åˆ†äº«
share: true
baidushare: true
showshare: true

# ç™¾åº¦ã€è°·æ­Œç«™é•¿éªŒè¯ã€‚å¡«å†™ HTML æ ‡ç­¾ content
# Site Verification for Google and Baidu. HTML label content.
# google_site: # pFW527fHrjfI0si2w4NQ0w3cTw12AvvuohAu1PUfqKA
# baidu_site: #c167b9feb4f0b208b712c79629c188e4

# Fill in Google Analytics tracking ID, #e.g. UA-XXXXX-X, or Baidu Analytics hash key
# google_analytics: xxxxx
# baidu_analytics: xxxxxx

# ä¸è’œå­ç½‘ç«™è®¡æ•°è®¾ç½®
# http://ibruce.info/2015/04/04/busuanzi/
visit_counter:
  on: true
  site_visit: æå®¢åˆ°è®¿æ•°
  page_visit: æœ¬é¡µé˜…è¯»é‡

# Aæ ‡ç­¾æç¤º
TipTitle: true
# Loading
# Loading: true
